manifest = "81e63df72503c517e7a650368dbef8c0baf3c8330d57db7b607e96d34cf4f8e2"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.50.0" ]
revision = "0af936e42c3db7c0f8a63e21265a645b70abb9cb"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.50.0" ]
revision = "279b99e09f2d86b2ccd97d2c6ebd37a9f6003c94"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.50.0" ]
revision = "daa51fdabbb2f0d42d395700ce5696c15a5e5d07"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.50.0" ]
revision = "7a95ba736b9be014028bf95deeeb5ccb06f8588b"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.50.0" ]
revision = "af76a5aef78b01d8e4b520133233a12fd69fe304"
