manifest = "5b343959450ef1ca90316ed6f783b239e87ed65c9c77ee600ee94e87eb0eaf21"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.41.0" ]
revision = "c32805df725494aca225f78f2d64b24bdf99e56a"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.41.0" ]
revision = "3dd65e69f2a9ed5bfc98d36329c9e832a650cf2b"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.41.0" ]
revision = "37f6440c2fea2aa756087b8f7c8274c9ee4081a6"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.41.0" ]
revision = "c848776c45974808d87763367162d9ab445c323e"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.41.0" ]
revision = "231c5eb4d0a10b0daa8950d2c91a07e2bfda5a2d"
